server:
  port: 8080
  servlet:    context-path: /gateway
  
spring:
  application:    name: gateway

eureka:
  instance:    prefer-ip-address: true  client:    register-with-eureka: true
    fetch-registry: true #exclusivo do gateway
    service-url:      defaultZone: http://localhost:8081/eureka/
      
zuul:
  sensitive-headers: Cookie
  
jwt:
  config:
    login-url: /auth/login
    type: signed
    
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000